name: epitech_intra_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  dartx: ^0.7.1
  dio: ^4.0.0
  equatable: ^2.0.3
